name: Common Ci
on:
  workflow_call:
    inputs:
      component_name:
        required: true
        type: string
      app_type:
        required: true
        type: string

jobs:
  Download-Dependencies-dockerbuild:
    runs-on: self-hosted
    steps:
      - name: check out repo code
        uses: actions/checkout@v4
      - name: CHeck
        run: echo ${{ inputs.component_name }} ${GITHUB_SHA}
      - name: Download Dependencies and Build Docker Image
        run: |
          if [ "${{ inputs.app_type }}" == "nodejs" ]; then
            npm install
          elif [ "${{ inputs.app_type }}" == "maven" ]; then
            mvn package
          fi
          docker build -t 886436958775.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.component_name }}:${GITHUB_SHA} .

  Docker-n-Push:
    runs-on: self-hosted
    needs: Download-Dependencies-dockerbuild
    steps:
      - name: check out repo code
        uses: actions/checkout@v4

      - name: Docker Build and Push
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 886436958775.dkr.ecr.us-east-1.amazonaws.com
          docker push 886436958775.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.component_name }}:${GITHUB_SHA}

  Dev-Deployment:
    runs-on: self-hosted
    needs: Docker-n-Push
    steps:
      - name: check out repo code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-helm

      - name: Deploy
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          aws eks update-kubeconfig --name dev
          bash argocd.sh ${{ inputs.component_name }} dev ${GITHUB_SHA}

  QA-Deployment:
    runs-on: self-hosted
    needs: Dev-Deployment
    steps:
      - name: check out repo code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-helm

      - name: Setup PATH and Deploy to QA
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
#          aws eks update-kubeconfig --name dev
#          make component=${{ inputs.component_name }} env=qa

  UAT-Deployment:
    runs-on: self-hosted
    needs: QA-Deployment
    steps:
      - name: check out repo code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-helm

      - name: Setup PATH and Deploy to UAT
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
#         aws eks update-kubeconfig --name dev
#         make component=${{ inputs.component_name }} env=uat

  PROD-Deployment:
    runs-on: self-hosted
    needs: UAT-Deployment
    steps:
      - name: check out repo code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-helm

      - name: Setup PATH and Deploy to PROD
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
#         aws eks update-kubeconfig --name dev
#         make component=${{ inputs.component_name }} env=prod
